server:
  port: 8088
  
logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd
  h2:
    console:
      enabled: true
    database:
      url: jdbc:h2:mem:testdb
      
management:
  endpoints:
    web:
      exposure:
        include: "*"